title: Welcome to Xander Rosado-Sessa's Tech portfolio!
description: Welcome to my digital portfolio! This is a space where I have gathered projects that showcase what I have learned and how I approach problem-solving. This space showcases my practical experience and problem-solving capabilities in designing, implementing, and securing robust IT solutions. I invite you to explore these examples to gain a comprehensive understanding of my approach and dedication to tackling complex technological challenges!
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
